origin: "/Users/ethanwater/Downloads/"
images: "/Users/ethanwater/Documents/images/"
texts: "/Users/ethanwater/Documents/texts/"
misc: "/Users/ethanwater/Documents/misc/"
custom_test: 
  name: golang
  path: "/Users/ethanwater/Desktop/code"
  ext: ".go .golang" 
