origin:
  name: origin
  path: "/Users/ethanwater/Downloads/"
  ext: ""
texts: 
  name: TEXTS
  path: "/Users/ethanwater/Documents/docs/"
  ext: ".txt .doc .docx .pages .pdf"
images: 
  name: IMAGES
  path: "/Users/ethanwater/Documents/images/"
  ext: ".jpg .png .jpeg .gif"
custom_test: 
  name: GOLANG
  path: "/Users/ethanwater/Documents/golang/"
  ext: ".go .golang" 

